defaults: &defaults
  adapter: postgresql
  encoding: unicode
  pool: 20
  username: aimeesimone
  password: 

development:
  <<: *defaults
  database: happymedium_development
  host: localhost

test:
  <<: *defaults
  database: happymedium_test

production:
  <<: *defaults
  database: happymedium_development
